

spring:
   application:
      name: Demo1
   profiles:
      active: #spring.profiles.active#
      group:
         dev:
            - dev
           #- api-docs
           # Uncomment to activate TLS for the dev profile
           #- tls
#   jmx:
#      enabled: false
   output:
      ansi:
         console-available: false
         
         
   data:
      jpa:
         repositories:
            bootstrap-mode: deferred
   jpa:
      open-in-view: false
      properties:
          hibernate.jdbc.time_zone: UTC
          hibernate.id.new_generator_mappings: true
          hibernate.connection.provider_disables_autocommit: true #spring.profiles.active#
          #hibernate.cache.use_second_level_cache: true
          #hibernate.cache.use_query_cache: false
          #hibernate.generate_statistics: false
          # modify batch size as necessary
          #hibernate.jdbc.batch_size: 25
          hibernate.jdbc.batch_size: 50
          hibernate.order_inserts: true
          hibernate.order_updates: true
          hibernate.query.fail_on_pagination_over_collection_fetch: true
          hibernate.query.in_clause_parameter_padding: true
      hibernate:
         ddl-auto: none
         naming:
            physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
            implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  


